title: Grégoire LAURENT # your name (or website title) here
logo: "/images/Greg_Robin2_cut.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst interested in ML projects
  <br><br>
  Repository of projects I worked on either during my free time or EPFL curriculum
  <br><br>
  <a href="https://www.linkedin.com/in/gregoirelaurent/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-S9LCE0CWYM # your Google Analytics tracking ID here 
