title: Grégoire LAURENT # your name (or website title) here
logo: "/images/Greg_Robin2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst interested in ML projects
  <br><br>
  Repository of projects from course at EPFL in Lausanne as well on my free time
  <br><br>
  <a href="https://www.linkedin.com/in/gregoirelaurent/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
